# infra/docker-compose.yml
services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: global-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8181:81"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-nw

  adminer:
    image: adminer
    container_name: global-adminer
    restart: unless-stopped
    # Pas besoin de ports ici, on y accèdera via NPM
    networks:
      - proxy-nw

networks:
  proxy-nw:
    external: true