services:
  php-app:
    build: .
    container_name: school-management-php
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:           <-- NE METS PAS DE SECTION PORTS ICI
    #   - "9000:9000"  <-- C'est CA qui créerait le conflit avec Portainer
    user: "${UID:-1000}:${GID:-1000}" # Utilise ton ID utilisateur courant
    volumes:
      - /home/mohamed/docker/school-app:/var/www/html
    networks:
      - proxy-nw

  # AJOUTE CE SERVICE NGINX
  web-server:
    image: nginx:alpine
    container_name: school-web
    volumes:
      - /home/mohamed/docker/school-app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # On va créer ce fichier
    networks:
      - proxy-nw
  # DB
  postgres-db:
    image: postgres:15-alpine
    container_name: school-db
    environment:
      - POSTGRES_USER=casaos
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_DB=school_db
    volumes:
      - /DATA/AppData/postgres:/var/lib/postgresql/data
    networks:
      - proxy-nw

  mysql-db:
    image: mariadb:10.11
    container_name: school-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: school_mysql_db
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
    volumes:
      - /DATA/AppData/mysql-data:/var/lib/mysql
    networks:
      - proxy-nw

  adminer:
    image: adminer
    container_name: school-adminer
    restart: unless-stopped
    ports:
      - "8090:8080"
    networks:
      - proxy-nw
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-db # Définit Postgres par défaut

networks:
  proxy-nw:
    external: true