---
config:
  theme: neo
---
classDiagram
direction LR

class User {
  +id : int
  +name : string
  +email : string
  +role : string
}

class Eleve {
  +id : int
  +nom : string
  +prenom : string
  +promotion_id : int
}

class Promotion {
  +id : int
  +nom : string
  +date_debut : date
  +date_fin : date
  +specialite_id : int
}

class Specialite {
  +id : int
  +nom : string
  +duree_annees : int
}

class Phase {
  +id : int
  +nom : string
  +ordre : int
}

class PromotionPhase {
  +id : int
  +promotion_id : int
  +phase_id : int
  +date_debut : date
  +date_fin : date
  +is_active : bool
}

class Matiere {
  +id : int
  +nom : string
  +specialite_id : int
}

class PhaseMatiere {
  +id : int
  +phase_id : int
  +matiere_id : int
  +coefficient : float
}

class Note {
  +id : int
  +eleve_id : int
  +matiere_id : int
  +phase_id : int
  +valeur : float
}

User "1" --> "0..*" Eleve : gère
Promotion "1" --> "0..*" Eleve : contient
Specialite "1" --> "0..*" Promotion : définit
Specialite "1" --> "0..*" Matiere : possède
Specialite "1" --> "0..*" Phase : structure

Promotion "1" --> "0..*" PromotionPhase : planifie
Phase "1" --> "0..*" PromotionPhase : est programmée

Phase "1" --> "0..*" PhaseMatiere : comprend
Matiere "1" --> "0..*" PhaseMatiere : est affectée

Eleve "1" --> "0..*" Note : reçoit
Phase "1" --> "0..*" Note : concerne
Matiere "1" --> "0..*" Note : évalue