server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public; # <--- Pointage vers le dossier public Laravel

    # 1. Redirection du WebSocket de Vite (HMR) vers Windows
    location /@vite/ {
        proxy_pass http://192.168.1.2:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # 2. Redirection des assets de développement (JS/JSX/CSS) vers Windows
    location /resources/ {
        proxy_pass http://192.168.1.2:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
      
        # On définit un résolveur interne Docker
        resolver 127.0.0.11 valid=30s;
        set $upstream_php php_app1_si;
        fastcgi_pass $upstream_php:9000;
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}