# avant
# mohamed in 🌐 casaos-server in /🔒
#❯ sudo docker network create web-gateway
#[sudo] password for mohamed:
#1d74e82308ea0b00ea34ce7265f5b51dcaa52b991077387dfa7e6c4371c308b1
# proxy-server/docker-compose.yml
#services:
#  nginx-proxy:
#    image: nginx:alpine
#    container_name: global-proxy
#    ports:
#      - "80:80"
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
#    networks:
#      - web-gateway
#
#networks:
#  web-gateway:
#    external: true
services:
  nginx-proxy:
    cpu_shares: 90
    command: [ ]
    deploy:
      resources:
        limits:
          memory: "1803550720"
    image: jc21/nginx-proxy-manager:latest
    #    networks:
    #      mail-network: null
    networks:
      - proxy-nw
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
      - mode: ingress
        target: 81
        published: "81"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/mohamed/docker/mailserver/docker-data/npm/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /home/mohamed/docker/mailserver/docker-data/npm/letsencrypt
        target: /etc/letsencrypt
        bind:
          create_host_path: true
      - type: bind
        source: /home/mohamed/docker/mailserver/certs/server.crt
        target: /data/custom_ssl/server.crt
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/mohamed/docker/mailserver/certs/server.key
        target: /data/custom_ssl/server.key
        read_only: true
        bind:
          create_host_path: true
networks:
  proxy-nw:
    external: true