# app1/docker-compose.yml
services:
  php_app1_si:
    build:
      context: ./php
      args:
        - USER_ID=1000 # Votre ID utilisateur Linux
    container_name: php-app1-si
    volumes:
      - ./src:/var/www/html # Votre code source Laravel
    networks:
      - proxy-nw
      - internal-app1-si

  db_app1_si:
    image: mariadb:10.11 # ou mysql
    container_name: db-app1-si # <-- C'est ce nom qu'il faudra taper dans Adminer
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: si_v1
      MYSQL_USER: si_v1
      MYSQL_PASSWORD: si_v1
    volumes:
      - /DATA/AppData/mysql-data_si:/var/lib/mysql
    networks:
      #- web-gateway # Indispensable pour que l'Adminer global le voie
      - proxy-nw          # On utilise directement le nom réel
      - internal-app1-si

networks:
  proxy-nw:
    external: true
  #web-gateway:
   # external: true
   # name: proxy-nw  # "web-gateway" dans ce fichier est en fait "proxy-nw" sur le serveur
  internal-app1-si: # Réseau privé pour que PHP parle à sa DB sans voir la DB de l'App 2
    driver: bridge

volumes:
  db_data1_si: