services:
  adminer:
    image: adminer
    container_name: global-adminer
    restart: unless-stopped
    # Pas besoin d'exposer le port 8080 vers l'extérieur ici
    # car on va y accéder via NPM de façon sécurisée.
    networks:
      - proxy-nw
    environment:
      - ADMINER_DEFAULT_SERVER=db_app1_si # Pré-remplissage optionnel
networks:
  proxy-nw:
    #name: proxy-nw # Force le nom pour qu'il soit reconnu par les autres stacks
    external: true
    #driver: bridge