version: '3.8'

services:
  greenmail:
    image: greenmail/standalone:2.1.11
    container_name: greenmail
    restart: unless-stopped
    ports:
      - "3143:143"  # Mappe le port IMAP 143 du conteneur vers 3143 sur votre PC
      - "3025:25"   # Mappe le port SMTP 25 du conteneur vers 3025 sur votre PC
    environment:
      # Inclus explicitement hostname=0.0.0.0 et définit l'utilisateur
      # - GREENMAIL_OPTS=-Djava.net.preferIPv4Stack=true -Dgreenmail.smtp -Dgreenmail.imap -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=admin@exemple.com:secret123
      - GREENMAIL_OPTS=-Djava.net.preferIPv4Stack=true -Dgreenmail.startup.timeout=10000 -Dgreenmail.setup.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.users=admin@exemple.com:secret123
  webmail:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # Connexion directe à GreenMail en interne sur le port 143
      - ROUNDCUBEMAIL_DEFAULT_HOST=zero://greenmail
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=zero://greenmail
      - ROUNDCUBEMAIL_SMTP_PORT=25
    depends_on:
      - greenmail
